branches:
  only:
    - dev

language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev

before_script:
  - mkdir build
  - cd build
  - cmake -DQT_SDK_DIR=$QTDIR ../cmake

script: make

notifications:
  email:
    - alex@alexchi.me
  on_success: change
  on_failure: always

